glob: introduce subpackage to match capture and replace using globbing patterns
darvaza-proxy/sidecar pull request #29
Opened 2023-12-25 17:58 UTC by amery

2023-12-26 13:22 UTC, karasz requested changes

2023-12-26 13:22 UTC, karasz commented on pkg/glob/glob.go
> +// this file is a slight variation of
either `slightly modified` or `light`....

2023-12-26 13:22 UTC, karasz commented on pkg/glob/glob.go
> +const matchTimeout = 10 * time.Second
thx ;-)

2023-12-26 13:22 UTC, karasz commented on pkg/glob/glob.go
> +
I have a slight preference towards:
```go
if m, err:=g.r.FindStringMatch(fixture); err!=nil{
core.PanicWrap(err,"regexp2.Regexp")
}
```

2023-12-26 13:24 UTC, karasz commented on pkg/glob/glob.go
> +// this file is a slight variation of
but slight variation might work

2023-12-26 16:42 UTC, amery commented on pkg/glob/glob.go
> +
problem there is the scope of `m`

2023-12-26 16:49 UTC, amery commented on pkg/glob/glob.go
> +
replaced with a `switch`, better?

2023-12-26 16:50 UTC, amery commented
rebased and amended as requested

2023-12-27 00:09 UTC, amery commented
Fixed refactoring residues

2023-12-27 10:21 UTC, karasz approved these changes
\o/

2023-12-27 10:22 UTC, merged

2023-12-27 13:54 UTC, amery commented
`darvaza.org/sidecar@v0.2.0` tagged